# Generated by Django 5.2.8 on 2025-11-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_content_remove_post_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_en',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_zh',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
