# Generated by Django 5.2.8 on 2025-11-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_posttag_post_posttag_post_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post_posttag',
            unique_together={('post', 'tag')},
        ),
    ]
